### ISSUE TITLE
E117: Unknown function: LaTeXtoUnicode#Refresh

### ISSUE THREAD

**Issue by sunaku** [JuliaLang/julia-vim#35]
Hello,

The latest commit f68b890453f0a02194f4805a6c8d034d9b326652 introduced a bug whereby the following errors occur on _all_ filetypes (instead of just the Julia filetype):

```
Error detected while processing BufEnter Auto commands for "*":
".xmodmaprc" 64L, 2328C
Error detected while processing FileType Auto commands for "*":
E117: Unknown function: LaTeXtoUnicode#Refresh
Error detected while processing BufEnter Auto commands for "*":
E117: Unknown function: LaTeXtoUnicode#Refresh
Error detected while processing VimEnter Auto commands for "*":
E117: Unknown function: LaTeXtoUnicode#Init
```

Thanks for your consideration.

**Comment by korya** [comment]
Same here:

```
Error detected while processing FileType Auto commands for "*":
E117: Unknown function: LaTeXtoUnicode#Refresh
Error detected while processing BufEnter Auto commands for "*":
E117: Unknown function: LaTeXtoUnicode#Refresh
Press ENTER or type command to continue
```

**Comment by carlobaldassi** [comment]
@korya could you provide instructions (and any additional detail) that allow to reproduce the issue?

**Comment by korya** [comment]
I have figured it out. It seems to be caused by lazy-loading the plugin:

```vim
Plug 'JuliaLang/julia-vim', { 'for': 'julia' }
```

After I replaced it with

```vim
Plug 'JuliaLang/julia-vim'
```

the problem disappeared.

Anyway, I believe that using `autocmd FileType *` for Julia plugin is an overkill. If you believe that `LaTeXtoUnicode` funtcionality is a killer feature for vim, you could just release it as a separate plugin.

**Comment by carlobaldassi** [comment]
Ah ok. Yes, that is a known issue, it's even documented in the installation instructions. The plugin is mostly lazy-loaded anyway.

The problem with separating the julia-specific part from the LaTeXtoUnicode part is 1) julia needs it, a julia plugin without it is IMO unthinkable, and 2) vim plugin managers don't typically have a way to specify dependencies.

**Comment by korya** [comment]
In https://github.com/JuliaEditorSupport/julia-vim/pull/45#issuecomment-73384085 you said:

> This seems exactly like #35. Calling the autocmds on * is intentional, and useful since it allows to use LaTeX substitutions with other filetypes. 

What I tried to say is if `LaTeXtoUnicode` functionality is so useful for different filetypes it makes sense to expose it as a separate plugin and specify in your docs that julia-vim depends on it and it should be installed.

When this functionality is bundled within julia-vim plugin, I think the best approach is to limit `LaTeXtoUnicode` to Julia file type only by default, and allow the user to decide whether it is an important enough feature to be enabled for other file types.

**Comment by carlobaldassi** [comment]
It is indeed only enabled by default on Julia file types. But it needs to potentially be loadable on other file types, for which it just needs to initialize some stuff. Unless you activate it on other file types, it won't do anything then, and all the functions are lazy-loaded anyway.

I completely agree that it would make sense to have two separate plugins, and I would love to have a solution to that. The problem is the one I wrote above. Just documenting requirements is not a satisfactory solution, unfortunately.
