### ISSUE TITLE
Different unicode VIM versus Julia interpreter

### ISSUE THREAD

**Issue by juliohm** [JuliaLang/julia-vim#77]
When I type `\triangleleft` and press TAB in Julia and in VIM, I get different triangles. Could you please confirm the issue?

**Comment by carlobaldassi** [comment]
If you are using julia 0.4, it's because it's changed in julia 0.5, from [WHITE LEFT-POINTING SMALL TRIANGLE](http://www.fileformat.info/info/unicode/char/25c3/index.htm) to [WHITE LEFT-POINTING TRIANGLE](http://www.fileformat.info/info/unicode/char/25c1/index.htm), which is arguably more correct. The LaTeX table is usually synced with the development version.

(I also noticed that the [Julia documentation](https://github.com/JuliaLang/julia/blob/master/doc/manual/unicode-input-table.rst) is not up to date, and consequently the julia-vim plugin docs are out-of-sync too.)

I don't know what could be done about this on a general level, other than hoping that these kind of things stabilize. But if you want to use the table for a particular julia version (e.g. for julia 0.4) you should just need to run the [autoload/generate_latex_symbols_table.jl](https://github.com/JuliaLang/julia-vim/blob/7faa591517b1ff0531508d47cac0c2c1893f472e/autoload/generate_latex_symbols_table.jl) script with that version of julia, inside the autoload directory.

**Comment by juliohm** [comment]
Makes sense @carlobaldassi , I will just close the issue and wait the unicode to stabilize.
